"""LangChain platform adapter."""

import os
import shutil
from pathlib import Path
from typing import Any, Dict, Optional

from .base import BaseAdapter

# Template for LangChain memory bridge (injected into user workspace)
_MEMORY_BRIDGE_TEMPLATE = '''"""
AgentForge Memory Bridge — LangChain
Auto-generated by `agentforge init --platform langchain`

Provides a LangChain-compatible ChromaDB VectorStore backed by your
AgentForge memory system. Import this in your agent code:

    from memory_bridge import vector_store, retriever

Then use it in your chain:

    from langchain.chains import RetrievalQA
    qa = RetrievalQA.from_chain_type(llm=llm, retriever=retriever)
"""

from pathlib import Path

MEMORY_PATH = Path("{memory_path}")

try:
    from langchain_chroma import Chroma
    from langchain_community.embeddings import HuggingFaceEmbeddings
except ImportError:
    raise ImportError(
        "LangChain Chroma integration not found. "
        "Install with: pip install langchain-chroma langchain-community sentence-transformers"
    )

_embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vector_store = Chroma(
    collection_name="agent_memory",
    persist_directory=str(MEMORY_PATH / "chroma_db"),
    embedding_function=_embeddings,
)

retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={{"k": 5}},
)

__all__ = ["vector_store", "retriever"]
'''

# Template for LangChain HealthKit callback handler
_HEALTHKIT_CALLBACK_TEMPLATE = '''"""
AgentForge HealthKit Callbacks — LangChain
Auto-generated by `agentforge init --platform langchain`

Monitors LangChain chain/agent runs and writes metrics to HealthKit.

Usage in your agent code:
    from healthkit_callbacks import HealthKitCallbackHandler
    handler = HealthKitCallbackHandler()
    chain = MyChain(..., callbacks=[handler])
"""

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Union
from uuid import UUID

HEALTHKIT_PATH = Path("{healthkit_path}")
METRICS_FILE = HEALTHKIT_PATH / "langchain_metrics.jsonl"
HEALTHKIT_PATH.mkdir(parents=True, exist_ok=True)

try:
    from langchain_core.callbacks.base import BaseCallbackHandler
    from langchain_core.outputs import LLMResult
except ImportError:
    raise ImportError(
        "langchain-core not found. Install with: pip install langchain-core"
    )


class HealthKitCallbackHandler(BaseCallbackHandler):
    """LangChain callback handler that logs metrics to AgentForge HealthKit."""

    def __init__(self) -> None:
        super().__init__()
        self._run_start: Dict[str, float] = {{}}

    def _write(self, record: Dict[str, Any]) -> None:
        with open(METRICS_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\\n")

    def on_llm_start(
        self,
        serialized: Dict[str, Any],
        prompts: List[str],
        *,
        run_id: UUID,
        **kwargs: Any,
    ) -> None:
        self._run_start[str(run_id)] = time.time()
        self._write({{
            "event": "llm_start",
            "run_id": str(run_id),
            "model": serialized.get("id", ["unknown"])[-1],
            "prompt_tokens": sum(len(p.split()) for p in prompts),
            "ts": self._run_start[str(run_id)],
        }})

    def on_llm_end(
        self,
        response: LLMResult,
        *,
        run_id: UUID,
        **kwargs: Any,
    ) -> None:
        elapsed = time.time() - self._run_start.pop(str(run_id), time.time())
        token_usage = {{}}
        if response.llm_output:
            token_usage = response.llm_output.get("token_usage", {{}})
        self._write({{
            "event": "llm_end",
            "run_id": str(run_id),
            "elapsed_s": round(elapsed, 3),
            "token_usage": token_usage,
            "ts": time.time(),
        }})

    def on_llm_error(
        self,
        error: BaseException,
        *,
        run_id: UUID,
        **kwargs: Any,
    ) -> None:
        self._write({{
            "event": "llm_error",
            "run_id": str(run_id),
            "error": str(error),
            "ts": time.time(),
        }})

    def on_chain_start(
        self,
        serialized: Dict[str, Any],
        inputs: Dict[str, Any],
        *,
        run_id: UUID,
        **kwargs: Any,
    ) -> None:
        self._run_start[str(run_id)] = time.time()
        self._write({{
            "event": "chain_start",
            "run_id": str(run_id),
            "chain": serialized.get("id", ["unknown"])[-1],
            "ts": self._run_start[str(run_id)],
        }})

    def on_chain_end(
        self,
        outputs: Dict[str, Any],
        *,
        run_id: UUID,
        **kwargs: Any,
    ) -> None:
        elapsed = time.time() - self._run_start.pop(str(run_id), time.time())
        self._write({{
            "event": "chain_end",
            "run_id": str(run_id),
            "elapsed_s": round(elapsed, 3),
            "ts": time.time(),
        }})

    def on_agent_action(
        self,
        action: Any,
        *,
        run_id: UUID,
        **kwargs: Any,
    ) -> None:
        self._write({{
            "event": "agent_action",
            "run_id": str(run_id),
            "tool": getattr(action, "tool", "unknown"),
            "ts": time.time(),
        }})
'''


class LangChainAdapter(BaseAdapter):
    """Adapter for the LangChain agent framework."""

    name: str = "langchain"

    def __init__(self) -> None:
        self.workspace_path = Path.home() / ".agentsforge" / "langchain"

    # ------------------------------------------------------------------ #
    # BaseAdapter interface                                                #
    # ------------------------------------------------------------------ #

    def detect(self) -> bool:
        """Detect if LangChain is installed."""
        try:
            import langchain  # noqa: F401
            return True
        except ImportError:
            return False

    def get_workspace(self) -> Optional[Path]:
        """Return the workspace directory, creating it if necessary."""
        self.workspace_path.mkdir(parents=True, exist_ok=True)
        return self.workspace_path

    def get_config(self) -> Dict[str, Any]:
        """Get LangChain configuration (env vars + workspace path)."""
        config: Dict[str, Any] = {
            "platform": "langchain",
            "workspace": str(self.workspace_path),
        }
        # Surface useful env vars if present
        for key in ("LANGCHAIN_API_KEY", "LANGCHAIN_TRACING_V2", "OPENAI_API_KEY"):
            val = os.environ.get(key)
            if val:
                config[key.lower()] = "***" if "key" in key.lower() else val
        return config

    def inject_memory(self, memory_path: Path) -> bool:
        """Drop a LangChain-compatible memory bridge into the workspace."""
        ws = self.get_workspace()
        if ws is None:
            return False
        bridge_path = ws / "memory_bridge.py"
        bridge_path.write_text(
            _MEMORY_BRIDGE_TEMPLATE.format(memory_path=memory_path),
            encoding="utf-8",
        )
        return True

    def inject_healthkit(self, healthkit_path: Path) -> bool:
        """Drop a HealthKit callback handler into the workspace."""
        ws = self.get_workspace()
        if ws is None:
            return False
        cb_path = ws / "healthkit_callbacks.py"
        cb_path.write_text(
            _HEALTHKIT_CALLBACK_TEMPLATE.format(healthkit_path=healthkit_path),
            encoding="utf-8",
        )
        return True

    # ------------------------------------------------------------------ #
    # Helpers                                                              #
    # ------------------------------------------------------------------ #

    def write_example(self) -> Path:
        """Write a minimal example agent that uses memory + healthkit."""
        ws = self.get_workspace()
        example = ws / "example_agent.py"
        example.write_text(
            '"""Example LangChain agent wired to AgentForge memory + HealthKit."""\n'
            "# Run: python example_agent.py\n\n"
            "from memory_bridge import retriever\n"
            "from healthkit_callbacks import HealthKitCallbackHandler\n\n"
            "# Plug the retriever into any LangChain chain:\n"
            "#   from langchain.chains import RetrievalQA\n"
            "#   qa = RetrievalQA.from_chain_type(llm=your_llm, retriever=retriever,\n"
            "#                                    callbacks=[HealthKitCallbackHandler()])\n"
            "print('AgentForge ✓  — memory bridge + healthkit ready')\n",
            encoding="utf-8",
        )
        return example
