"""Standalone (raw Python, framework-agnostic) platform adapter."""

from pathlib import Path
from typing import Any, Dict, Optional

from .base import BaseAdapter

# Template: memory setup script dropped into user workspace
_MEMORY_SETUP_TEMPLATE = '''"""
AgentForge Memory Setup — Standalone
Auto-generated by `agentforge init --platform standalone`

Provides a minimal ChromaDB + SentenceTransformers vector store backed by your
AgentForge memory system.  No LangChain or framework dependency required.

Usage:
    from memory_setup import MemoryStore
    mem = MemoryStore()
    mem.add("key decision: chose PostgreSQL over MySQL for prod")
    results = mem.query("database choice", n=3)
    for r in results:
        print(r["document"])
"""

from pathlib import Path
from typing import Any, Dict, List, Optional

MEMORY_PATH = Path("{memory_path}")
CHROMA_DB   = MEMORY_PATH / "chroma_db"

try:
    import chromadb
    from chromadb.utils import embedding_functions
except ImportError:
    raise ImportError(
        "chromadb not found. Install with: pip install chromadb sentence-transformers"
    )


class MemoryStore:
    """Thin wrapper around ChromaDB using the AgentForge memory database."""

    def __init__(
        self,
        collection: str = "agent_memory",
        model: str = "sentence-transformers/all-MiniLM-L6-v2",
    ) -> None:
        self._client = chromadb.PersistentClient(path=str(CHROMA_DB))
        self._ef = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name=model
        )
        self._col = self._client.get_or_create_collection(
            name=collection,
            embedding_function=self._ef,
            metadata={{"hnsw:space": "cosine"}},
        )

    def add(self, text: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Add a document and return its auto-generated ID."""
        import hashlib, time
        doc_id = hashlib.sha1(f"{{text}}{{time.time()}}".encode()).hexdigest()[:16]
        self._col.add(
            documents=[text],
            metadatas=[metadata or {{}}],
            ids=[doc_id],
        )
        return doc_id

    def query(self, text: str, n: int = 5) -> List[Dict[str, Any]]:
        """Query the memory store and return top-n results."""
        results = self._col.query(query_texts=[text], n_results=n)
        out = []
        for doc, meta, dist in zip(
            results["documents"][0],
            results["metadatas"][0],
            results["distances"][0],
        ):
            out.append({{"document": doc, "metadata": meta, "distance": dist}})
        return out

    def count(self) -> int:
        """Return total document count in the collection."""
        return self._col.count()
'''

# Template: healthkit setup dropped into user workspace
_HEALTHKIT_SETUP_TEMPLATE = '''"""
AgentForge HealthKit Setup — Standalone
Auto-generated by `agentforge init --platform standalone`

Lightweight structured logging for standalone Python agents.
Writes JSONL metrics that the HealthKit monitor can read.

Usage:
    from healthkit_setup import HealthKit
    hk = HealthKit(agent_name="my_agent")
    with hk.span("llm_call", model="gpt-4o"):
        response = your_llm_call(prompt)
    hk.log("info", "Task completed", task="summarise_email")
"""

import json
import time
import contextlib
from pathlib import Path
from typing import Any, Optional

HEALTHKIT_PATH = Path("{healthkit_path}")
HEALTHKIT_PATH.mkdir(parents=True, exist_ok=True)


class HealthKit:
    """Minimal structured metric logger for standalone Python agents."""

    def __init__(self, agent_name: str = "standalone_agent") -> None:
        self.agent_name = agent_name
        self._log_file = HEALTHKIT_PATH / f"{{agent_name}}_metrics.jsonl"

    def _write(self, record: dict) -> None:
        record.setdefault("agent", self.agent_name)
        record.setdefault("ts", time.time())
        with open(self._log_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\\n")

    def log(self, level: str, message: str, **kwargs: Any) -> None:
        """Write a structured log entry."""
        self._write({{"level": level, "message": message, **kwargs}})

    @contextlib.contextmanager
    def span(self, name: str, **kwargs: Any):
        """Context manager that times a code block and logs start/end."""
        start = time.time()
        self._write({{"event": f"{{name}}_start", **kwargs}})
        try:
            yield
        except Exception as exc:
            self._write({{"event": f"{{name}}_error", "error": str(exc), **kwargs}})
            raise
        finally:
            elapsed = time.time() - start
            self._write({{"event": f"{{name}}_end", "elapsed_s": round(elapsed, 3), **kwargs}})
'''


class StandaloneAdapter(BaseAdapter):
    """Adapter for raw Python projects (no framework dependency)."""

    name: str = "standalone"

    def __init__(self) -> None:
        self.workspace_path = Path.home() / ".agentsforge" / "standalone"

    # ------------------------------------------------------------------ #
    # BaseAdapter interface                                                #
    # ------------------------------------------------------------------ #

    def detect(self) -> bool:
        """Always available — standalone is the universal fallback."""
        return True

    def get_workspace(self) -> Optional[Path]:
        """Return the workspace directory, creating it if necessary."""
        self.workspace_path.mkdir(parents=True, exist_ok=True)
        return self.workspace_path

    def get_config(self) -> Dict[str, Any]:
        """Return basic standalone configuration."""
        return {
            "platform": "standalone",
            "workspace": str(self.workspace_path),
        }

    def inject_memory(self, memory_path: Path) -> bool:
        """Drop a framework-agnostic MemoryStore helper into the workspace."""
        ws = self.get_workspace()
        if ws is None:
            return False
        setup_path = ws / "memory_setup.py"
        setup_path.write_text(
            _MEMORY_SETUP_TEMPLATE.format(memory_path=memory_path),
            encoding="utf-8",
        )
        return True

    def inject_healthkit(self, healthkit_path: Path) -> bool:
        """Drop a HealthKit structured-logging helper into the workspace."""
        ws = self.get_workspace()
        if ws is None:
            return False
        setup_path = ws / "healthkit_setup.py"
        setup_path.write_text(
            _HEALTHKIT_SETUP_TEMPLATE.format(healthkit_path=healthkit_path),
            encoding="utf-8",
        )
        return True

    # ------------------------------------------------------------------ #
    # Helpers                                                              #
    # ------------------------------------------------------------------ #

    def write_example(self) -> Path:
        """Write a minimal standalone example that shows memory + healthkit."""
        ws = self.get_workspace()
        example = ws / "example_agent.py"
        example.write_text(
            '"""Example standalone Python agent using AgentForge memory + HealthKit."""\n'
            "# Run: python example_agent.py\n\n"
            "from memory_setup import MemoryStore\n"
            "from healthkit_setup import HealthKit\n\n"
            "mem = MemoryStore()\n"
            "hk  = HealthKit(agent_name='my_agent')\n\n"
            "# Store a memory\n"
            "mem.add('decided to use PostgreSQL for the production database')\n\n"
            "# Query memories\n"
            "with hk.span('memory_query'):\n"
            "    results = mem.query('database decision', n=3)\n\n"
            "for r in results:\n"
            "    print(r['document'])\n\n"
            "hk.log('info', 'Example agent ran successfully')\n"
            "print('AgentForge ✓  — standalone memory + healthkit ready')\n",
            encoding="utf-8",
        )
        return example
